baseURL = "https://aquastripe.github.io/paper-notes/"
languageCode = "zh-TW"
title = "論文筆記"
theme = "hugo-geekdoc"
hasCJKLanguage = true

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
